{
    "name":"Customer Management System",
    "author":"Sri Sathya",
    "version":"18.0",
    "depends":["base","contacts","sale","sale_management","account",],
    "data":[
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence.xml",
        "views/view_respartner.xml",
        "views/customer_followup.xml",
        "views/view_shipment_doc.xml",
        "views/customerdetails.xml",
        "views/view_invoices.xml",
        "data/customer_confirm_mail.xml",
        "wizard/customer_invoices_wizard.xml",
        "wizard/sale_order_wizard.xml",
        "report/report_customer_pdf_template.xml",
        "report/report_customer_landscape.xml",
        "report/salesperson_pdf_fromtodates_template.xml",
        "report/report.xml",
        "report/wizard_reports.xml",
        "views/menu.xml",
    ],
}